language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
    - secure: >-
        lrV+ArWbH2E1uxyRT9KfM0kr/Ih9GqZRL8mZxASTKcYKvD08mKNF6bktmx0tjx49Wm7dlMmcsLHZm1PaXvVSTq7VEHneEaRvFCSTX/OAIFlNMy7JodlAQQUOILNeGrZR2koIii6rK0oI8aG/XnWr12D1br9GFzaM+ZUBydVmH6spHJQM2I5elMJPc7uYIwwBU/nZRJhzFCFWpCJ5A1FsFM42tGhY8m/gsS6rbyKP6n4t8+CRcJjKY+aCLP37yYFYykR1eqZhQF06nsEH9uFvoLssn2VZQtiIY6Ep7BCp33d8mqyOuKTLehzuqO2+p3+VdMeVumkIc0yXJt8a0MFA6CRhtT6OxBciKYaD+oiGyjV9uBN9+/L9tLySd/11daSJLb9FIecGcMscAbeZMk1fiQbjb7MoMxZEubDm4dIh3cTbtbSgdgQ9Ki2qrct24Xpm+1mw6xZa1CZF+s0uYNmCmg45Pu3jpysg3KzXZbAiIns6bN7SwJdVqBg9tqI+8JHakBLlGAxzVRS587uBm9J0YRlwq2ufEvMsUu1QPjFfD2X1EIyRhiFbYl48uxVZDM7fRJG3kjrBWDHnHkMW/EUB7G/znXbMmQOcP4ZTKB8Qiu8+aRRYX+JiGW/W5dor9SK7D2tn2q0tgVCM4U9W/A6serlSX6gjXxLQ//CY/1yfU1E=
    - secure: >-
        HKjepWjLOqjruWOGPYax7hQP8G1o+KTSiEaprLYIq7ObCIiqrpqaQRNLKZdrafTa/cS4EtwEk87XPjzbUJ7cBgqbrlPEx9SEH1aYhACqxUk4u2j4aUe1dThadxswwiwibmA35B4CThchJAGzgxHysQQyMPsJxjydQEfhWSiMirAzCiwlfmQVI4rJFoWdimrI4o9yGIMx6Hu2+4jsyRXtFrRXiO9PNxSQlec93782dMfkEyagM7gU+XWlZP+qhOt3inlomIx2/7XnUzO7rtuA93/OOgh93AwhSWRcHsW5bAqlC4DA35lf+PrSKhABbJkX4aRoohtyj00za04D+oma/XBgC+zVLmorlDx0RTGeeRF6YrtqZMLnTSWIu+Zk9oquH7OqdFtSoFIeGFgyLwHuBm0534cNHirmNJm4qoS2yDdmAzbbt6J3JU7bGRniLGbpyi5V/0R9HU3/wHUh5pmGe/VabTsFNszzkczSZzUPYqmTDzCmqOKVMRZvxkBJ3+a/mR9XDmmXWs7eecVqJ64ON0qIG/fkwGtYYrFfhqeoDISGEOAegU+wKhMfXMspufuRxcX4yKaVHiRgqR6ltlJNm/GWb//lDz9YJJemvQ48+2/0C7JKPYapLef+R154kx2tWTqFM7AacltIAxTwu0d4qzK6EsahlyW8USlur7/F/4A=
